# Generated by Django 3.0.1 on 2019-12-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomtext',
            old_name='disable',
            new_name='enabled',
        ),
    ]
