# Generated by Django 3.0.1 on 2019-12-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_searchqueries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchQueries',
            new_name='SearchQuery',
        ),
    ]
