# Generated by Django 3.0.1 on 2019-12-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20191220_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'verbose_name_plural': 'Search queries'},
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='shown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to='search.RandomText'),
        ),
    ]
