# Generated by Django 3.0.1 on 2019-12-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_remove_searchquery_query'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchQuery',
            new_name='ShowLog',
        ),
    ]
