# Generated by Django 3.0.1 on 2019-12-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20191220_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showlog',
            options={'verbose_name_plural': 'Show log'},
        ),
    ]
